# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Generate committed Pydantic models from WikiSkill's canonical OKF contracts."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from wikiskill.models import generate_pydantic_code

ROOT = Path(__file__).parent.parent
KNOWLEDGE = ROOT / "knowledge"
TARGET = ROOT / "src" / "wikiskill" / "generated" / "okf_models.py"
HEADER = (
    '"""Generated by scripts/generate_okf_models.py from canonical OKF contracts.\n\n'
    "Do not edit by hand. Regenerate from specs/*.md + specs/*.schema.sql.\n"
    '"""\n\n'
)


def expected_content() -> str:
    """Return the deterministic committed representation of the current contracts."""
    generated = generate_pydantic_code(KNOWLEDGE)
    return HEADER + generated.lstrip()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the committed source is stale")
    args = parser.parse_args()

    expected = expected_content()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != expected:
            print(
                "Generated OKF models are stale; run "
                "`uv run python scripts/generate_okf_models.py`.",
                file=sys.stderr,
            )
            return 1
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(expected, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
